### ISSUE TITLE
Plugin causes AppleScripts calling tell application "System Events" to run extremely slow on Mac

### ISSUE THREAD

**Issue by jmrq** [smitmartijn/streamdeck-zoom-plugin#23] opened 2021-02-03 00:47 UTC
Stream Deck Software Version 4.9.2 (13193)
System: MacBook Air running macOS Catalina (10.15.7)

Plugin is causing any AppleScript which calls `tell application "System Events"` to run extremely slow.  Simple scripts that run almost instantly without the plug-in installed are taking any where from 6 to 10 seconds to run!!!  Only solution for now was to uninstall plugin.

I'm happy to provide any more details or info if it would helpful.

**Comment by smitmartijn** [comment] 2021-02-16 18:35
I can't reproduce this and have not found any other reports. I'm assuming it'll have something to do with your computer, but I honestly have no idea where to start looking for that - sorry. Considering no others have come around to suggest a troubleshooting method, I'm closing this.

**Closed by smitmartijn** 2021-02-16 18:35 UTC
