### ISSUE TITLE
Plugin introduces severe lag into Stream Deck application

### ISSUE THREAD

**Issue by tsvoronos** [smitmartijn/streamdeck-zoom-plugin#22] opened 2021-01-27 13:19 UTC
I'm running an M1 MBP with Big Sur 11.2 and Stream Deck 4.9.2. The Zoom plugin makes the application slow to a crawl, where I can't drag buttons around and there's a significant delay in even typing into the search bar. Uninstalling the plugin and restarting Stream Deck makes the issue go away.

I have my Stream Deck unplugged so know it isn't hardware related.

**Comment by smitmartijn** [comment] 2021-02-16 18:35
I can't reproduce this and have not found any other reports. I'm assuming it'll have something to do with your computer, but I honestly have no idea where to start looking for that - sorry. Considering no others have come around to suggest a troubleshooting method, I'm closing this.

**Closed by smitmartijn** 2021-02-16 18:35 UTC
