### ISSUE TITLE
Mute/Video toggle not working

### ISSUE THREAD

**Issue by sangyye** [smitmartijn/streamdeck-zoom-plugin#14] opened 2020-11-23 13:34 UTC
Hello there,
Just today I updated to the latest version of the plug-in with the new icons, I think this is version 2.1. prior to that the buttons where working. The leave button still works fine.
I have already reinstalled the plugin and restarted all apps. I‘m on MacOS 10.15.7 and Zoom 5.4.4

Can someone confirm or help me fix this?

**Comment by istriepling** [comment] 2020-12-21 20:33
Hello,
unfortunately, I only can confirm. My Mac is running on the latest macOS Big Sur and Zoom 5.4.7. Stream Deck software is up to date as well.
Please help to fix. It's such a great plugin.
Thank you so much!

**Comment by derekedelaney** [comment] 2020-12-29 18:14
I did run into this as well. When I first installed it, it worked out of the box. Now it doesn't.  I had to update the setting in the zoom application and turn on the [global keyboard](https://github.com/smitmartijn/streamdeck-zoom-plugin#installation) shortcuts. That did fix the issue for me.

**Comment by tkorner** [comment] 2020-12-30 08:08
Hello, 
same here. I could only solve it by using global hot keys and uninstall this great plugin. Thus, if you could have a look, please! Thank you!

**Comment by agiledivider** [comment] 2021-01-13 16:13
Same for me.

**Comment by smitmartijn** [comment] 2021-01-26 09:29
For those of you where it works on 1.0, but not 2.x: are you using a different language than English on the Zoom client?

**Comment by tkorner** [comment] 2021-01-26 09:35
yes, I'm using the German version of Zoom and Streamdeck

**Comment by sangyye** [comment] 2021-01-26 09:41
Interesting, I changed the language of Zoom to English and now the buttons are working again. So the Problem was that my default language is different from English.

**Comment by smitmartijn** [comment] 2021-01-26 09:44
Yes, because the plugin presses a menu item to toggle things. I.e., for video, it clicks "Meeting" -> "Start Video". 

#21 reminded me that those menu items will be in different languages when the Zoom client is set to something other than English.

**Comment by istriepling** [comment] 2021-01-26 15:56
I am using the German Version as well. Is there any possibility to create a German Version of the plugin. Unfortunately I can't code, but I would like to help with the translation.

Von: Martijn Smit <notifications@github.com>
Antworten an: smitmartijn/streamdeck-zoom-plugin <reply@reply.github.com>
Datum: Dienstag, 26. Januar 2021 um 10:44
An: smitmartijn/streamdeck-zoom-plugin <streamdeck-zoom-plugin@noreply.github.com>
Cc: Ingo Striepling <ingo@striepling.de>, Comment <comment@noreply.github.com>
Betreff: Re: [smitmartijn/streamdeck-zoom-plugin] Mute/Video toggle not working (#14)


Yes, because the plugin presses a menu item to toggle things. I.e., for video, it clicks "Meeting" -> "Start Video".

#21<https://github.com/smitmartijn/streamdeck-zoom-plugin/issues/21> reminded me that those menu items will be in different languages when the Zoom client is set to something other than English.

**Comment by tkorner** [comment] 2021-01-26 16:23
> Interesting, I changed the language of Zoom to English and now the buttons are working again. So the Problem was that my default language is different from English.

I can confirm, it works in English. If you are using a Mac with Big Sur, you have to change the language in the general language setting of the computer (but restricted to the app) due to the zoom app doesn't allow you to choose the language.

**Comment by moohkooh** [comment] 2021-02-12 06:32
I run also into this issue with. The reason why I bought the stream deck was to control my zoom meeting. I will check the code maybe i get release a german version of this plugin.

**Comment by smitmartijn** [comment] 2021-02-16 17:52
I have just pushed code that allows you to customize the text of the menu items the plugin automatically clicks. After testing this with a Zoom client set to German, it should fix this issue. I'm packaging it up now and sending it to Elgato so they can put version 3.0 on the store. Closing this issue in the meantime, please re-open if you can't get it to work when it's available.

**Closed by smitmartijn** 2021-02-16 17:52 UTC

**Comment by sammer2001** [comment] 2021-03-18 19:59
I'm having issues but using both Stream Deck software and Zoom in English.
